-- MySQL Script generated by MySQL Workbench
-- Thu Jan 28 17:57:36 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema TAREFAS_DIARIAS
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `TAREFAS_DIARIAS` ;

-- -----------------------------------------------------
-- Schema TAREFAS_DIARIAS
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TAREFAS_DIARIAS` DEFAULT CHARACTER SET utf8mb4 ;
SHOW WARNINGS;
USE `TAREFAS_DIARIAS` ;

-- -----------------------------------------------------
-- Table `alunos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `alunos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `alunos` (
  `email` VARCHAR(60) NOT NULL,
  `nome` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `disciplinas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `disciplinas` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `disciplinas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `logins`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `logins` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `logins` (
  `email` VARCHAR(60) NOT NULL,
  `senha` VARCHAR(20) NOT NULL,
  `autorizado` TINYINT NOT NULL DEFAULT 0,
  `habilitado` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`email`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `professores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `professores` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `professores` (
  `email` VARCHAR(60) NOT NULL,
  `nome` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tarefas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tarefas` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tarefas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(60) NOT NULL,
  `pontuacao` DOUBLE NOT NULL,
  `tarefaDisponibilizada` TINYINT NOT NULL DEFAULT 0,
  `tarefaExcluida` TINYINT NULL DEFAULT 0,
  `disciplinas_id` INT NOT NULL,
  `alunos_email` VARCHAR(60) NOT NULL,
  `professores_email` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
